export const data = [
   {
      name: 'MacDonalds',
      products: [
         {
            title: 'Product MacDonalds',
            description: 'lorem ipsum dolor, let count if',
            price: 14,
            _id: '647202e150861c44dab677f7',
         },
         {
            title: 'Product MacDonalds',
            description: 'lorem ipsum dolor, let count if',
            price: 24,
            _id: '647202e150861c44dab677f8',
         },
         {
            title: 'Product MacDonalds',
            description: 'lorem ipsum dolor, let count if',
            price: 8,
            _id: '647202e150861c44dab677f9',
         },
         {
            title: 'Product MacDonalds',
            description: 'lorem ipsum dolor, let count if',
            price: 68,
            _id: '647202e150861c44dab677fa',
         },
         {
            title: 'Product MacDonalds',
            description: 'lorem ipsum dolor, let count if',
            price: 10,
            _id: '647202e150861c44dab677fb',
         },
         {
            title: 'Product MacDonalds',
            description: 'lorem ipsum dolor, let count if',
            price: 64,
            _id: '647202e150861c44dab677fc',
         },
         {
            title: 'Product MacDonalds',
            description: 'lorem ipsum dolor, let count if',
            price: 14,
            _id: '647202e150861c44dab677fd',
         },
         {
            title: 'Product MacDonalds',
            description: 'lorem ipsum dolor, let count if',
            price: 50,
            _id: '647202e150861c44dab677fe',
         },
         {
            title: 'Product MacDonalds',
            description: 'lorem ipsum dolor, let count if',
            price: 32,
            _id: '647202e150861c44dab677ff',
         },
         {
            title: 'Product MacDonalds',
            description: 'lorem ipsum dolor, let count if',
            price: 20,
            _id: '647202e150861c44dab67800',
         },
         {
            title: 'Product MacDonalds',
            description: 'lorem ipsum dolor, let count if',
            price: 62,
            _id: '647202e150861c44dab67801',
         },
         {
            title: 'Product MacDonalds',
            description: 'lorem ipsum dolor, let count if',
            price: 2,
            _id: '647202e150861c44dab67802',
         },
         {
            title: 'Product MacDonalds',
            description: 'lorem ipsum dolor, let count if',
            price: 47,
            _id: '647202e150861c44dab67803',
         },
         {
            title: 'Product MacDonalds',
            description: 'lorem ipsum dolor, let count if',
            price: 0,
            _id: '647202e150861c44dab67804',
         },
      ],
      _id: '647202e150861c44dab677f6',
   },
   {
      name: 'Silpo',
      products: [
         {
            title: 'Product Silpo',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 90,
            _id: '647202e150861c44dab67806',
         },
         {
            title: 'Product Silpo',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 85,
            _id: '647202e150861c44dab67807',
         },
         {
            title: 'Product Silpo',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 35,
            _id: '647202e150861c44dab67808',
         },
         {
            title: 'Product Silpo',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 76,
            _id: '647202e150861c44dab67809',
         },
         {
            title: 'Product Silpo',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 36,
            _id: '647202e150861c44dab6780a',
         },
         {
            title: 'Product Silpo',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 51,
            _id: '647202e150861c44dab6780b',
         },
         {
            title: 'Product Silpo',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 14,
            _id: '647202e150861c44dab6780c',
         },
         {
            title: 'Product Silpo',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 45,
            _id: '647202e150861c44dab6780d',
         },
         {
            title: 'Product Silpo',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 64,
            _id: '647202e150861c44dab6780e',
         },
         {
            title: 'Product Silpo',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 10,
            _id: '647202e150861c44dab6780f',
         },
         {
            title: 'Product Silpo',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 35,
            _id: '647202e150861c44dab67810',
         },
         {
            title: 'Product Silpo',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 87,
            _id: '647202e150861c44dab67811',
         },
         {
            title: 'Product Silpo',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 97,
            _id: '647202e150861c44dab67812',
         },
         {
            title: 'Product Silpo',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 38,
            _id: '647202e150861c44dab67813',
         },
      ],
      _id: '647202e150861c44dab67805',
   },
   {
      name: 'Just Eat',
      products: [
         {
            title: 'Product Just Eat',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 34,
            _id: '647202e150861c44dab67815',
         },
         {
            title: 'Product Just Eat',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 35,
            _id: '647202e150861c44dab67816',
         },
         {
            title: 'Product Just Eat',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 28,
            _id: '647202e150861c44dab67817',
         },
         {
            title: 'Product Just Eat',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 39,
            _id: '647202e150861c44dab67818',
         },
         {
            title: 'Product Just Eat',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 13,
            _id: '647202e150861c44dab67819',
         },
         {
            title: 'Product Just Eat',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 69,
            _id: '647202e150861c44dab6781a',
         },
         {
            title: 'Product Just Eat',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 56,
            _id: '647202e150861c44dab6781b',
         },
         {
            title: 'Product Just Eat',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 1,
            _id: '647202e150861c44dab6781c',
         },
         {
            title: 'Product Just Eat',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 95,
            _id: '647202e150861c44dab6781d',
         },
         {
            title: 'Product Just Eat',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 88,
            _id: '647202e150861c44dab6781e',
         },
         {
            title: 'Product Just Eat',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 38,
            _id: '647202e150861c44dab6781f',
         },
         {
            title: 'Product Just Eat',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 25,
            _id: '647202e150861c44dab67820',
         },
         {
            title: 'Product Just Eat',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 56,
            _id: '647202e150861c44dab67821',
         },
         {
            title: 'Product Just Eat',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 76,
            _id: '647202e150861c44dab67822',
         },
      ],
      _id: '647202e150861c44dab67814',
   },
   {
      name: 'George`s',
      products: [
         {
            title: 'Product George`s',
            description: 'Tu autem negas fortem esse quemquam posse, qui dolorem malum putet. Audeo dicere, inquit.',
            price: 7,
            _id: '647202e150861c44dab67824',
         },
         {
            title: 'Product George`s',
            description: 'Tu autem negas fortem esse quemquam posse, qui dolorem malum putet. Audeo dicere, inquit.',
            price: 76,
            _id: '647202e150861c44dab67825',
         },
         {
            title: 'Product George`s',
            description: 'Tu autem negas fortem esse quemquam posse, qui dolorem malum putet. Audeo dicere, inquit.',
            price: 37,
            _id: '647202e150861c44dab67826',
         },
         {
            title: 'Product George`s',
            description: 'Tu autem negas fortem esse quemquam posse, qui dolorem malum putet. Audeo dicere, inquit.',
            price: 48,
            _id: '647202e150861c44dab67827',
         },
         {
            title: 'Product George`s',
            description: 'Tu autem negas fortem esse quemquam posse, qui dolorem malum putet. Audeo dicere, inquit.',
            price: 55,
            _id: '647202e150861c44dab67828',
         },
         {
            title: 'Product George`s',
            description: 'Tu autem negas fortem esse quemquam posse, qui dolorem malum putet. Audeo dicere, inquit.',
            price: 17,
            _id: '647202e150861c44dab67829',
         },
         {
            title: 'Product George`s',
            description: 'Tu autem negas fortem esse quemquam posse, qui dolorem malum putet. Audeo dicere, inquit.',
            price: 50,
            _id: '647202e150861c44dab6782a',
         },
         {
            title: 'Product George`s',
            description: 'Tu autem negas fortem esse quemquam posse, qui dolorem malum putet. Audeo dicere, inquit.',
            price: 3,
            _id: '647202e150861c44dab6782b',
         },
         {
            title: 'Product George`s',
            description: 'Tu autem negas fortem esse quemquam posse, qui dolorem malum putet. Audeo dicere, inquit.',
            price: 81,
            _id: '647202e150861c44dab6782c',
         },
         {
            title: 'Product George`s',
            description: 'Tu autem negas fortem esse quemquam posse, qui dolorem malum putet. Audeo dicere, inquit.',
            price: 91,
            _id: '647202e150861c44dab6782d',
         },
         {
            title: 'Product George`s',
            description: 'Tu autem negas fortem esse quemquam posse, qui dolorem malum putet. Audeo dicere, inquit.',
            price: 96,
            _id: '647202e150861c44dab6782e',
         },
         {
            title: 'Product George`s',
            description: 'Tu autem negas fortem esse quemquam posse, qui dolorem malum putet. Audeo dicere, inquit.',
            price: 24,
            _id: '647202e150861c44dab6782f',
         },
         {
            title: 'Product George`s',
            description: 'Tu autem negas fortem esse quemquam posse, qui dolorem malum putet. Audeo dicere, inquit.',
            price: 72,
            _id: '647202e150861c44dab67830',
         },
         {
            title: 'Product George`s',
            description: 'Tu autem negas fortem esse quemquam posse, qui dolorem malum putet. Audeo dicere, inquit.',
            price: 55,
            _id: '647202e150861c44dab67831',
         },
      ],
      _id: '647202e150861c44dab67823',
   },
   {
      name: 'Glovo',
      products: [
         {
            title: 'Product Glovo',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 95,
            _id: '647202e150861c44dab67833',
         },
         {
            title: 'Product Glovo',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 31,
            _id: '647202e150861c44dab67834',
         },
         {
            title: 'Product Glovo',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 86,
            _id: '647202e150861c44dab67835',
         },
         {
            title: 'Product Glovo',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 5,
            _id: '647202e150861c44dab67836',
         },
         {
            title: 'Product Glovo',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 34,
            _id: '647202e150861c44dab67837',
         },
         {
            title: 'Product Glovo',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 6,
            _id: '647202e150861c44dab67838',
         },
         {
            title: 'Product Glovo',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 85,
            _id: '647202e150861c44dab67839',
         },
         {
            title: 'Product Glovo',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 70,
            _id: '647202e150861c44dab6783a',
         },
         {
            title: 'Product Glovo',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 80,
            _id: '647202e150861c44dab6783b',
         },
         {
            title: 'Product Glovo',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 42,
            _id: '647202e150861c44dab6783c',
         },
         {
            title: 'Product Glovo',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 9,
            _id: '647202e150861c44dab6783d',
         },
         {
            title: 'Product Glovo',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 57,
            _id: '647202e150861c44dab6783e',
         },
         {
            title: 'Product Glovo',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 0,
            _id: '647202e150861c44dab6783f',
         },
         {
            title: 'Product Glovo',
            description: 'Inde sermone vario sex illa a Dipylo stadia confecimus. Graecum enim hunc versum nostis',
            price: 44,
            _id: '647202e150861c44dab67840',
         },
      ],
      _id: '647202e150861c44dab67832',
   },
]
